Use pasa_anto;
Insert Into pas_tip_ins ( ide_ins, tip_ins, tip_uni)
    VALUES ( 0, 'Cremalleras','Unidades'),
    ( 0, 'Botonería','Unidades'),
    ( 0, 'Broches','Unidades'),
    ( 0, 'Adornos','Unidades'),
    ( 0, 'Lentejuelas','Unidades'),
    ( 0, 'Agujas', 'Unidades'),
    ( 0, 'Hebillas','Unidades'),
    ( 0, 'Bordados','Unidades'),
    ( 0, 'Cintas', 'Centímetros'),
    ( 0, 'Apliques', 'Unidades'),
    ( 0, 'Telas', 'Metros');

Insert Into pas_tip_pre ( ide_pre, tip_pre) 
    VALUES ( 0, 'Abrigo'),
    ( 0, 'Blue Jeans'),
    ( 0, 'Botas'),
    ( 0, 'Bragas'),
    ( 0, 'Bufanda'),
    ( 0, 'Cartera'),
    ( 0, 'Chal'),
    ( 0, 'Chaleco'),
    ( 0, 'Chandal'),
    ( 0, 'Chaqueta'),
    ( 0, 'Cinturon'),
    ( 0, 'Collar'),
    ( 0, 'Falda'),
    ( 0, 'Franela'),
    ( 0, 'Franelilla'),
    ( 0, 'Gabardina'),
    ( 0, 'Gorra'),
    ( 0, 'Gorro Tejido'),
    ( 0, 'Medias'),
    ( 0, 'Mochila'),
    ( 0, 'Pantalon'),
    ( 0, 'Pañuelo'),
    ( 0, 'Pijama'),
    ( 0, 'Pulsera'),
    ( 0, 'Short'),
    ( 0, 'Sombrero'),
    ( 0, 'Sueter'),
    ( 0, 'Sujetador'),
    ( 0, 'Tacones'),
    ( 0, 'Traje de Baño'),
    ( 0, 'Vestido'),
    ( 0, 'Zapatos');