-- MySQL Script generated by MySQL Workbench
-- 01/01/13 01:37:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- DATABASE pasa_anto
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `pasa_anto` ;

-- -----------------------------------------------------
-- DATABASE pasa_anto
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `pasa_anto` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `pasa_anto` ;

-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_tip_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_tip_ins` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_tip_ins` (
  `ide_tip` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tip_ins` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_tip` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_tip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_ins` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_ins` (
  `ide_ins` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ide_tip` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `nom_ins` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `pre_ins` DECIMAL(12,2) NOT NULL,
  `can_ins` DECIMAL(5,2) NOT NULL,
  `est_ins` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_ins`),
  INDEX `fk_pas_ins_pas_tip_ins1_idx` (`ide_tip` ASC),
  CONSTRAINT `fk_pas_ins_pas_tip_ins1`
    FOREIGN KEY (`ide_tip`)
    REFERENCES `pasa_anto`.`pas_tip_ins` (`ide_tip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_tip_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_tip_pre` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_tip_pre` (
  `ide_tip` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tip_pre` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_tip` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_tip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_pre` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_pre` (
  `ide_pre` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ide_tip` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `nom_pre` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `can_pre` INT(4) NOT NULL,
  `cos_pre` DECIMAL(12,2) NOT NULL,
  `col_pre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_pre` TINYINT(1) NOT NULL,
  `des_pre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ide_pre`),
  INDEX `fk_pas_pre_pas_tip_pre1_idx` (`ide_tip` ASC),
  CONSTRAINT `fk_pas_pre_pas_tip_pre1`
    FOREIGN KEY (`ide_tip`)
    REFERENCES `pasa_anto`.`pas_tip_pre` (`ide_tip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_ins_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pas_anto`.`pas_ins_pre` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_ins_pre` (
  `ide_ins` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ide_pre` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `can` DECIMAL(5,2) NOT NULL,
  INDEX `fk_pas_ins_pre_pas_ins_idx` (`ide_ins` ASC),
  INDEX `fk_pas_ins_pre_pas_pre1_idx` (`ide_pre` ASC),
  CONSTRAINT `fk_pas_ins_pre_pas_ins`
    FOREIGN KEY (`ide_ins`)
    REFERENCES `pasa_anto`.`pas_ins` (`ide_ins`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_ins_pre_pas_pre1`
    FOREIGN KEY (`ide_pre`)
    REFERENCES `pasa_anto`.`pas_pre` (`ide_pre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `pasa_anto` ;

-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_car` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_car` (
  `ide_car` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tip_car` ENUM('administrador','vendedor(a)') CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `hor_tra` INT(2) NULL DEFAULT NULL,
  `pag_hor` DECIMAL(12,2) NULL DEFAULT NULL,
  PRIMARY KEY (`ide_car`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_cli`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_cli` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_cli` (
  `ced_cli` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `nom_cli` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `dir_cli` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `cor_cli` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `tel_cli` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `est_cli` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ced_cli`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_pro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_pro` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_pro` (
  `rif_pro` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `nom_pro` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `dir_pro` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `tel_pro` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `cor_pro` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `tip_pro` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `est_pro` TINYINT(1) NOT NULL,
  PRIMARY KEY (`rif_pro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_fac_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_fac_ins` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_fac_ins` (
  `ide_fac` INT(11) NOT NULL AUTO_INCREMENT,
  `rif_pro` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `mon_fac` DECIMAL(12,2) NOT NULL,
  `fec_fac` DATE NOT NULL,
  `est_fac` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_fac`),
  INDEX `fk_pas_fac_ins_pas_pro_idx` (`rif_pro` ASC),
  CONSTRAINT `fk_pas_fac_ins_pas_pro`
    FOREIGN KEY (`rif_pro`)
    REFERENCES `pasa_anto`.`pas_pro` (`rif_pro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_det_ins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_det_ins` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_det_ins` (
  `ide_fac` INT(11) NOT NULL,
  `ide_ins` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `can_com` DECIMAL(5,2) NOT NULL,
  INDEX `fk_pas_det_ins_pas_fac_ins1_idx` (`ide_fac` ASC),
  INDEX `fk_pas_det_ins_pas_ins1_idx` (`ide_ins` ASC),
  CONSTRAINT `fk_pas_det_ins_pas_fac_ins1`
    FOREIGN KEY (`ide_fac`)
    REFERENCES `pasa_anto`.`pas_fac_ins` (`ide_fac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_det_ins_pas_ins1`
    FOREIGN KEY (`ide_ins`)
    REFERENCES `pasa_anto`.`pas_ins` (`ide_ins`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_ped`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_ped` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_ped` (
  `ide_ped` INT(11) NOT NULL AUTO_INCREMENT,
  `ced_cli` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `fec_rea` DATE NOT NULL,
  `fec_ent` DATE NOT NULL,
  `est_ped` ENUM('cancelado','en proceso','realizado') CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  PRIMARY KEY (`ide_ped`),
  INDEX `fk_pas_ped_pas_cli1_idx` (`ced_cli` ASC),
  CONSTRAINT `fk_pas_ped_pas_cli1`
    FOREIGN KEY (`ced_cli`)
    REFERENCES `pasa_anto`.`pas_cli` (`ced_cli`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_tra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_tra` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_tra` (
  `ced_tra` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ide_car` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `nom_tra` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `dir_tra` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `cor_tra` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `tel_tra` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `cla_tra` CHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`ced_tra`),
  INDEX `fk_pas_tra_pas_car1_idx` (`ide_car` ASC),
  CONSTRAINT `fk_pas_tra_pas_car1`
    FOREIGN KEY (`ide_car`)
    REFERENCES `pasa_anto`.`pas_car` (`ide_car`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_det_ped`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_det_ped` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_det_ped` (
  `ide_ped` INT(11) NOT NULL,
  `ide_pas` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ced_tra` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `des_ped` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NULL DEFAULT NULL,
  `can_ped` INT(4) NOT NULL,
  `cos_uni` DECIMAL(12,2) NOT NULL,
  INDEX `fk_pas_det_ped_pas_ped1_idx` (`ide_ped` ASC),
  INDEX `fk_pas_det_ped_pas_tra1_idx` (`ced_tra` ASC),
  INDEX `fk_pas_det_ped_pas_pre1_idx` (`ide_pas` ASC),
  CONSTRAINT `fk_pas_det_ped_pas_ped1`
    FOREIGN KEY (`ide_ped`)
    REFERENCES `pasa_anto`.`pas_ped` (`ide_ped`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_det_ped_pas_pre1`
    FOREIGN KEY (`ide_pas`)
    REFERENCES `pasa_anto`.`pas_pre` (`ide_pre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_det_ped_pas_tra1`
    FOREIGN KEY (`ced_tra`)
    REFERENCES `pasa_anto`.`pas_tra` (`ced_tra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_fac_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_fac_pre` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_fac_pre` (
  `ide_fac` INT(11) NOT NULL AUTO_INCREMENT,
  `rif_pro` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `fec_fac` DATE NOT NULL,
  `mon_fac` DECIMAL(12,2) NOT NULL,
  `est_fac` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_fac`),
  INDEX `fk_pas_fac_pre_pas_pro1_idx` (`rif_pro` ASC),
  CONSTRAINT `fk_pas_fac_pre_pas_pro1`
    FOREIGN KEY (`rif_pro`)
    REFERENCES `pasa_anto`.`pas_pro` (`rif_pro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_det_pre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_det_pre` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_det_pre` (
  `ide_fac` INT(11) NOT NULL,
  `ide_pas` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `can_com` INT(4) NOT NULL,
  `cos_uni` DECIMAL(12,2) NOT NULL,
  INDEX `fk_pas_det_pre_pas_fac_pre1_idx` (`ide_fac` ASC),
  INDEX `fk_pas_det_pre_pas_pre1_idx` (`ide_pas` ASC),
  CONSTRAINT `fk_pas_det_pre_pas_fac_pre1`
    FOREIGN KEY (`ide_fac`)
    REFERENCES `pasa_anto`.`pas_fac_pre` (`ide_fac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_det_pre_pas_pre1`
    FOREIGN KEY (`ide_pas`)
    REFERENCES `pasa_anto`.`pas_pre` (`ide_pre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_iva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_iva` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_iva` (
  `ide_iva` INT(8) NOT NULL,
  `por_iva` DECIMAL(4,2) NOT NULL,
  `fec_act` DATE NOT NULL,
  `est_iva` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_iva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_ven`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_ven` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_ven` (
  `ide_fec` INT(11) NOT NULL AUTO_INCREMENT,
  `ced_cli` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ced_tra` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `ide_iva` INT(8) NOT NULL,
  `fec_fac` DATE NOT NULL,
  `nom_fac` DECIMAL(12,2) NOT NULL,
  `est_fac` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ide_fec`),
  INDEX `fk_pas_ven_pas_cli1_idx` (`ced_cli` ASC),
  INDEX `fk_pas_ven_pas_tra1_idx` (`ced_tra` ASC),
  INDEX `fk_pas_ven_pas_iva1_idx` (`ide_iva` ASC),
  CONSTRAINT `fk_pas_ven_pas_cli1`
    FOREIGN KEY (`ced_cli`)
    REFERENCES `pasa_anto`.`pas_cli` (`ced_cli`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_ven_pas_iva1`
    FOREIGN KEY (`ide_iva`)
    REFERENCES `pasa_anto`.`pas_iva` (`ide_iva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_ven_pas_tra1`
    FOREIGN KEY (`ced_tra`)
    REFERENCES `pasa_anto`.`pas_tra` (`ced_tra`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


-- -----------------------------------------------------
-- Table `pasa_anto`.`pas_det_ven`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pasa_anto`.`pas_det_ven` ;

CREATE TABLE IF NOT EXISTS `pasa_anto`.`pas_det_ven` (
  `ide_fec` INT(11) NOT NULL,
  `can_ven` INT(4) NOT NULL,
  `ide_pas` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  INDEX `fk_pas_det_ven_pas_ven1_idx` (`ide_fec` ASC),
  INDEX `fk_pas_det_ven_pas_pre1_idx` (`ide_pas` ASC),
  CONSTRAINT `fk_pas_det_ven_pas_pre1`
    FOREIGN KEY (`ide_pas`)
    REFERENCES `pasa_anto`.`pas_pre` (`ide_pre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pas_det_ven_pas_ven1`
    FOREIGN KEY (`ide_fec`)
    REFERENCES `pasa_anto`.`pas_ven` (`ide_fec`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish2_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
